
[[constraint]]
  name = "github.com/decred/dcrd"
  version = "1.2.0-rc1"

[[constraint]]
  name = "github.com/decred/dcrwallet"
  version = "1.2.0-rc1"

[[constraint]]
  name = "github.com/docker/docker"
  version = "17.03.2-ce"

[[constraint]]
  branch = "master"
  name = "github.com/marcopeereboom/go-homedir"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"
